version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        - VITE_API_BASE_URL=/api
        - VITE_WS_BASE_URL=/ws
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    networks:
      - app-network
    environment:
      - PORT=8080

networks:
  app-network:
    driver: bridge
