version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:8080
        - VITE_WS_BASE_URL=ws://localhost:8080
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"
